-- MySQL Script generated by MySQL Workbench
-- ter 06 dez 2016 00:36:01 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pseudoToFortran
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pseudoToFortran
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pseudoToFortran` DEFAULT CHARACTER SET utf8 ;
USE `pseudoToFortran` ;

-- -----------------------------------------------------
-- Table `pseudoToFortran`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pseudoToFortran`.`Usuario` (
  `nome` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(20) NULL,
  `cod` INT NOT NULL  AUTO_INCREMENT,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pseudoToFortran`.`Codigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pseudoToFortran`.`Codigo` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `codigo_pseudo` VARCHAR(1000) NOT NULL,
  `codigo_fortran` VARCHAR(1000) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_codigo_usuario_idx` (`id_usuario` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  CONSTRAINT `fk_codigo_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pseudoToFortran`.`Usuario` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
